### ISSUE TITLE
buffer dtype mismatch, expected "DTYPE T" but got "double"

### ISSUE THREAD

**Issue by tommyvcc** [andruekonst/weighted-random-survival-forest#3]
Dear Andruekonst

Thank you very much for the great work.
The package is working now on the example datasets.
However, when I do it on my own dataset, I get the following error on google colab :

 i indices: 83
Indices computed: #J = 55953
Indices after subspace selection: #J = 3000
Traceback (most recent call last):
  File "test_survival_forests_sample.py", line 139, in <module>
    fit_time, ci_weighted, ci_without_weights = test_on(dataset(test_size=test_size),
  File "test_survival_forests_sample.py", line 54, in test_on
    rf.fit(data_x_numeric, pd_y_values)
  File "/content/survival.py", line 327, in fit
    self.make_weights(x)
  File "/content/survival.py", line 369, in make_weights
    left = self.predict_trees_subset_row(q, x.loc[i])
  File "/content/survival.py", line 497, in predict_trees_subset_row
    subset_prediction = [self.predict_row(self.trees[i], row) for i in range(fst, fst + self.n_trees_in_subset)]
  File "/content/survival.py", line 497, in <listcomp>
    subset_prediction = [self.predict_row(self.trees[i], row) for i in range(fst, fst + self.n_trees_in_subset)]
  File "/content/survival.py", line 478, in predict_row
    return fast_implementations.compute_hazard(row[self.time_column],
  File "fast_implementations.pyx", line 26, in fast_implementations.compute_hazard
    def compute_hazard(float time, np.ndarray[DTYPE_t, ndim=1] count_0, np.ndarray[DTYPE_t, ndim=1] count_1, np.ndarray[DTYPE_t, ndim=1] t, int total):
ValueError: Buffer dtype mismatch, expected 'DTYPE_t' but got 'double'

**Comment by tommyvcc** [comment]
It was something wrong with my data. Sorted
